repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']  # Allow YAML with custom tags
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, docs, style, refactor, perf, test, build, ci, chore, revert]

  - repo: local
    hooks:
      - id: validate-yaml-schema
        name: Validate YAML schema syntax
        entry: yq eval '.' schema/workout-share-schema.yaml
        language: system
        files: ^schema/workout-share-schema\.yaml$
        pass_filenames: false

      - id: regenerate-json-schema
        name: Regenerate JSON schema from YAML
        entry: bash -c 'yq eval -o=json "." schema/workout-share-schema.yaml > schema/workout-share-schema.json'
        language: system
        files: ^schema/workout-share-schema\.yaml$
        pass_filenames: false

      - id: validate-json-schema
        name: Validate generated JSON schema syntax
        entry: jq empty schema/workout-share-schema.json
        language: system
        files: ^schema/workout-share-schema\.json$
        pass_filenames: false

      - id: validate-examples
        name: Validate example workout files
        entry: bash -c 'cd code && uv run validate.py ../examples'
        language: system
        files: ^examples/.*\.ya?ml$
        pass_filenames: false
